last test!!!

diff --git a/Flask/mysql-task/Jenkinsfile b/Flask/mysql-task/Jenkinsfile
--- a/Flask/mysql-task/Jenkinsfile
+++ b/Flask/mysql-task/Jenkinsfile
@@ -199,18 +199,26 @@ pipeline {
         stage('Run Docker Container "deploy"') {
             steps {
                 script {
-                        withCredentials([sshUserPrivateKey(credentialsId: 'instance-test', keyFileVariable: 'KEY_NAME', usernameVariable: 'ec2-user')]) {
-                            echo "Using Public IP: ${publicIp}"
-                            echo "Using SSH Key: ${KEY_NAME}"
-                            // Run Docker container on the EC2 instance
-                            def containerCommand = """
-                                ssh -o StrictHostKeyChecking=no -i ${KEY_NAME} ec2-user@${publicIp} << EOF
-                                    # Run a sample Docker container compose
-                                    docker-compose up -d
-                                EOF
-                            """
-                            sh(script: containerCommand)
-                            echo "Docker container is running on EC2 instance."
+                    withCredentials([sshUserPrivateKey(credentialsId: 'instance-test', keyFileVariable: 'KEY_NAME', usernameVariable: 'ec2-user')]) {
+                        echo "Using Public IP: ${publicIp}"
+                        echo "Using SSH Key: ${KEY_NAME}"
+
+                        // Run Docker container on the EC2 instance
+                        def containerCommand = """
+                            ssh -o StrictHostKeyChecking=no -i ${KEY_NAME} ec2-user@${publicIp} << 'EOF'
+                                # Ensure docker-compose is installed and accessible
+                                if ! command -v docker-compose &> /dev/null; then
+                                    echo "docker-compose not found!"
+                                    exit 1
+                                fi
+
+                                # Run the Docker Compose file
+                                cd /home/ec2-user
+                                docker-compose up -d
+                            EOF
+                        """
+                        sh(script: containerCommand)
+                        echo "Docker container is running on EC2 instance."
                     }
                 }
             }
